apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-monitoring
  namespace: {{ .Values.monitoring.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: prometheus
        image: "{{ .Values.monitoring.prometheus.image.repository }}:{{ .Values.monitoring.prometheus.image.tag }}"
        resources:
          {{- toYaml .Values.monitoring.prometheus.resources | nindent 12 }}
      - name: grafana
        image: "{{ .Values.monitoring.grafana.image.repository }}:{{ .Values.monitoring.grafana.image.tag }}"
        resources:
          {{- toYaml .Values.monitoring.grafana.resources | nindent 12 }}
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-grafana-pvc
