apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-grafana-pv
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.monitoring.grafana.persistence.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/grafana"
