apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-secrets
  namespace: {{ .Values.monitoring.namespace }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "1234"
