services:
  db:
    container_name: db
    restart: always
    image: postgres:16.1-alpine3.18
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $DB_NAME -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  app:
    build: .
    restart: on-failure
    container_name: app
    volumes:
      - .:/go/src/app
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - shared-network

volumes:
  db:

networks:
  internal:
    driver: bridge
  shared-network:
    external: true
