services:
  db:
    container_name: db
    restart: always
    image: redis:7.2.3-alpine
    volumes:
      - db:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  app:
    build: .
    restart: on-failure
    container_name: app
    volumes:
      - .:/usr/src/app
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - shared-network

volumes:
  db:

networks:
  internal:
    driver: bridge
  shared-network:
    external: true
