apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: user
  label: user-service

spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: app
        image: {{ .Values.appImage }}
      - name: db
        image: postgres
