apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /watcher
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-backend
            port:
              number: 80
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-monitoring
            port:
              number: 3000
      - path: /prometheus
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-monitoring
            port:
              number: 9090
