apiVersion: v1
kind: Namespace
metadata:
  name: { { .Values.app.namespace } }
---
apiVersion: v1
kind: Namespace
metadata:
  name: { { .Values.cache.namespace } }
---
apiVersion: v1
kind: Namespace
metadata:
  name: { { .Values.monitoring.namespace } }
