apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cache
  namespace: {{ .Values.cache.namespace }}
spec:
  selector:
    app: cache
  ports:
  - port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-monitoring
  namespace: {{ .Values.monitoring.namespace }}
spec:
  selector:
    app: monitoring
  ports:
  - name: grafana
    port: 3000
  - name: prometheus
    port: 9090
