apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-external
spec:
  type: ExternalName
  externalName: {{ .Release.Name }}-backend.{{ .Values.app.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-external
spec:
  type: ExternalName
  externalName: {{ .Release.Name }}-prometheus.{{ .Values.monitoring.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana-external
spec:
  type: ExternalName
  externalName: {{ .Release.Name }}-grafana.{{ .Values.monitoring.namespace }}
