apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.app.namespace }}
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cache
  namespace: {{ .Values.cache.namespace }}
  labels:
    app: cache
    access: internal
spec:
  type: ClusterIP
  selector:
    app: cache
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-monitoring
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: monitoring
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
    nodePort: 30300
  - name: prometheus
    port: 9090
    targetPort: 9090
    nodePort: 30090
