apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgres-pv
  namespace: {{ .Values.app.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.app.database.persistence.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"
