apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    matchLabels:
      type: local
  resources:
    requests:
      storage: {{ .Values.app.database.persistence.requests }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
