apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secrets
  namespace: {{ .Values.app.namespace }}
type: Opaque
stringData:
  DB_USER: db_user
  DB_PASSWORD: "1234"
  DB_NAME: watcher
  SECRET_KEY: "1234"
  MOVIE_DB_BASE_URL: https://api.themoviedb.org/3
  MOVIE_DB_ACCESS_TOKEN:
