"""Added User and WatchList tables

Revision ID: 4906c4231d87
Revises: 
Create Date: 2024-11-11 14:18:28.423432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4906c4231d87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_user',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('email', sa.String(50), nullable=False),
                    sa.Column('name', sa.String(50), nullable=False),
                    sa.Column('password', sa.String(255), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('genres', postgresql.ARRAY(
                        sa.String()), nullable=False),
                    sa.CheckConstraint(
                        "email ~* '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'", name='check_email_format'),
                    sa.CheckConstraint('age >= 15', name='check_age_minimum'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_custom_user_id'),
                    'custom_user', ['id'], unique=False)
    op.create_table('watchlist',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('movie_id', sa.Integer(), nullable=False),
                    sa.Column('is_complete', sa.Boolean(),
                              nullable=False, default=False),
                    sa.ForeignKeyConstraint(['user_id'], ['custom_user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'user_id', 'movie_id', name='unique_user_movie')
                    )
    op.create_index(op.f('ix_watchlist_id'), 'watchlist', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_id'), table_name='watchlist')
    op.drop_constraint('unique_user_movie', 'watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_user_id'), table_name='custom_user')
    op.drop_constraint('check_email_format', 'custom_user')
    op.drop_constraint('check_age_minimum', 'custom_user')
    op.drop_table('custom_user')
    # ### end Alembic commands ###
