# Prometheus service config
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: prometheus
    port: 80
    targetPort: 9090
    nodePort: 30090
---
# Grafana service config
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: monitoring
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - name: grafana
    port: 80
    targetPort: 3000
    nodePort: 30300
